# Generated by Django 3.2.6 on 2021-09-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_rating_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='geners',
            new_name='genres',
        ),
    ]
