# Generated by Django 3.2.6 on 2021-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_geners_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
